filebeat.inputs:
    - type: log
      enabled: true
      encoding: UTF-8
      paths:
        - "/var/logs/beats/1/*.json"
      tags: ["json"]

    - type: log
      enabled: true
      encoding: UTF-8
      paths:
        - "/var/logs/beats/2/*.csv"
      tags: ["csv"]

output.logstash:
  hosts: ["logstash:5044"]

setup.template.name: "filebeat"
setup.template.overwrite: false
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 1