# setting heap size using command: sysctl -w vm.max_map_count=262144

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es01
    volumes:
      - type: volume
        source: esdata01
        target: /usr/share/elasticsearch/esdata
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    environment:
      - node.name=es01
      - cluster.name=es-docker
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - username=elastic
      - password=elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es02
    volumes:
      - type: volume
        source: esdata02
        target: /usr/share/elasticsearch/esdata
    ports:
      - 9201:9201
      - 9301:9301
    networks:
      - elastic
    environment:
      - node.name=es02
      - cluster.name=es-docker
      - discovery.seed_hosts=es01,es03
      - username=elastic
      - password=elastic

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es03
    volumes:
      - type: volume
        source: esdata03
        target: /usr/share/elasticsearch/esdata
    ports:
      - 9202:9202
      - 9302:9302
    networks:
      - elastic
    environment:
      - node.name=es03
      - cluster.name=es-docker
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - username=elastic
      - password=elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.1
    container_name: logstash
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline/pip_test.config
        target: /usr/share/logstash/pipeline/pip_test.config
        read_only: true
    ports:
      - 5044:5044
    networks:
      - elastic
    depends_on:
      - es01
      - es02
      - es03

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.1
    # build: ./filebeat/
    container_name: filebeat
    volumes:
      - type: bind
        source: ./filebeat/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
      - type: bind
        source: ./logs/1
        target: /var/logs/beats/1
        read_only: true
      - type: bind
        source: ./logs/2
        target: /var/logs/beats/2
        read_only: true
    networks:
      - elastic
    depends_on:
      - es01
      - es02
      - es03
      - logstash

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local

networks:
  elastic:
    driver: bridge